%% SDPE MATLAB initialization script
% Project: PGS Single-Phase Inverter Common Control
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Platform-independent control contract shared by all pgs_sinv_rc projects.

%% Project metadata
PGS_SINV_RC_COMMON_SDPE_PROJECT_ID = 'pgs_sinv_rc_common';

PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-07-24';

%% Control Features
% Enable delayed insertion of the frequency-adaptive repetitive controller.
SINV_ENABLE_REPETITIVE_CONTROL = true;

% Enable grid-voltage feedforward for closed-current-loop build levels.
SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD = true;

%% Runtime
% Allow ENABLE_OPERATION to advance through the complete CiA402 startup sequence.
CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = true;

%% Requirement bindings
% Minimum voltage magnitude used by the P/Q reference generator.
CTRL_GRID_VMIN_PU = 0.1;

% SOGI PLL proportional gain.
CTRL_PLL_KP = 10.0;

% SOGI PLL integral time constant in seconds.
CTRL_PLL_TI = 0.02;

% PLL error-filter cutoff frequency in Hz.
CTRL_PLL_LPF_FC = 20.0;

% PLL frequency-error lock threshold in PU.
CTRL_SPLL_EPSILON = 0.005;

% Power measurement low-pass cutoff frequency in Hz.
CTRL_PQ_LPF_FC = 200.0;

% Peak current command limit in PU.
CTRL_CURRENT_LIMIT_PU = 0.9;

% Active-power command slew limit in PU/s.
CTRL_P_SLEW_PU_S = 5.0;

% Reactive-power command slew limit in PU/s.
CTRL_Q_SLEW_PU_S = 5.0;

% Current deadband used by PWM dead-time compensation.
CTRL_CURRENT_DB_PU = 0.01;

% QPR current-loop crossover target in Hz.
SINV_CURRENT_LOOP_BANDWIDTH_HZ = 600.0;

% Minimum fundamental tracked by FDRC in Hz.
CTRL_FDRC_MIN_FREQ = 45.0;

% Settling time before repetitive control starts learning.
SINV_FDRC_ENABLE_DELAY_MS = 300;

% Repetitive-control learning gain.
SINV_FDRC_LEARNING_GAIN = 0.10;

% FDRC robustness-filter cutoff frequency.
SINV_FDRC_Q_FILTER_HZ = 1000.0;

% Plant-delay compensation in controller samples.
SINV_FDRC_LEAD_STEPS = 3.0;

% Current-error threshold above which RC learning is frozen.
SINV_FDRC_FREEZE_ERROR_PU = 0.05;

% BUILD_LEVEL 1 sinusoidal H-bridge voltage amplitude.
SINV_LEVEL1_VOLTAGE_REF_PU = 0.35;

% Active-power outer-loop proportional gain.
SINV_POWER_LOOP_KP = 0.6;

% Active-power outer-loop integral gain per second.
SINV_POWER_LOOP_KI = 8.0;

% DC-bus outer-loop proportional gain.
SINV_DC_BUS_LOOP_KP = 0.8;

% DC-bus outer-loop integral gain per second.
SINV_DC_BUS_LOOP_KI = 12.0;

% Symmetric outer-loop active-power command limit.
SINV_OUTER_LOOP_POWER_LIMIT_PU = 0.65;

% Power and DC-bus outer-loop execution frequency.
SINV_OUTER_LOOP_FREQUENCY_HZ = 1000.0;

% Buck voltage-loop execution frequency.
SINV_BUCK_VOLTAGE_LOOP_FREQUENCY_HZ = 200.0;

% Buck voltage-loop proportional gain.
SINV_BUCK_VOLTAGE_LOOP_KP = 0.1;

% Buck voltage-loop integral gain per second.
SINV_BUCK_VOLTAGE_LOOP_KI = 15.0;

% Buck current-loop proportional gain.
SINV_BUCK_CURRENT_LOOP_KP = 0.20;

% Buck current-loop integral gain per second.
SINV_BUCK_CURRENT_LOOP_KI = 500.0;

% BUILD_LEVEL 2 peak current command with a resistive load.
SINV_LEVEL2_CURRENT_REF_PEAK_PU = 0.20;

% BUILD_LEVEL 3 signed grid active-power command; positive exports power.
SINV_LEVEL3_ACTIVE_POWER_REF_PU = 0.10;

% BUILD_LEVEL 3 grid reactive-power command.
SINV_LEVEL3_REACTIVE_POWER_REF_PU = 0.0;

% BUILD_LEVEL 4 measured active-power closed-loop target.
SINV_LEVEL4_ACTIVE_POWER_REF_PU = 0.15;

% BUILD_LEVEL 5 physical DC bus voltage target.
SINV_DC_BUS_REF_V = 80.0;

% BUILD_LEVEL 5 target displacement power-factor magnitude. Valid control range is 0.1 to 1.0.
SINV_POWER_FACTOR_REF = 1.0;

% BUILD_LEVEL 5 reactive-power direction for PF control. Use +1 or -1 to select the quadrature-current direction.
SINV_POWER_FACTOR_Q_SIGN = -1.0;

% BUILD_LEVEL 5 PF-to-Q calibration gain. It only scales the reactive-power command converted from PF_ref, compensating measured Q/P deviation without changing PF_ref magnitude or Q direction.
SINV_POWER_FACTOR_Q_GAIN = 1.06;

% Buck output voltage target.
SINV_BUCK_OUTPUT_REF_V = 60.0;

% Buck output-voltage reference soft-start slew rate in V/s. After Buck start conditions are met, the internal voltage reference ramps from 0 V to SINV_BUCK_OUTPUT_REF_V at this rate. This is the Buck soft-start parameter.
SINV_BUCK_VREF_SLEW_V_S = 120.0;

% Buck inductor-current command limit in ampere.
SINV_BUCK_CURRENT_LIMIT_A = 5.0;

% Minimum operation-enabled transition delay.
SINV_CIA402_OPERATION_ENABLE_DELAY_MS = 100;

% Minimum DC bus voltage before Buck soft-start is allowed.
SINV_BUCK_START_VBUS_MIN_V = 55.0;

% Delay after the Buck start condition is met before PWM compare ramps.
SINV_BUCK_START_DELAY_MS = 100;

% Buck duty-cycle lower clamp.
SINV_BUCK_DUTY_MIN = 0.0;

% Buck duty-cycle upper clamp.
SINV_BUCK_DUTY_MAX = 1.0;

% Maximum Buck current-loop duty correction around input-voltage feedforward.
SINV_BUCK_DUTY_TRIM_LIMIT = 0.03;

% Extra duty headroom above Buck voltage feedforward during startup and transients.
SINV_BUCK_DUTY_FF_MARGIN = 0.02;

% First-order low-pass coefficient for Buck input-voltage feedforward.
SINV_BUCK_VIN_FF_LPF_ALPHA = 0.006;

% Buck input-voltage feedforward blending gain; 0 disables source feedforward and 1 uses full Vref/Vin feedforward.
SINV_BUCK_DUTY_FF_GAIN = 0.15;

% Nominal grid frequency in Hz.
CTRL_GRID_FREQUENCY = 50.0;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
