%% SDPE MATLAB initialization script
% Project: PGS GFL Inverter F280039C IRIS Node
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Validated IRIS platform timing, sensing and resource bindings for the common GFL controller.

%% Project metadata
PGS_INV_GFL_IRIS_SDPE_PROJECT_ID = 'pgs_inv_gfl_f280039c_iris_node';

PGS_INV_GFL_IRIS_SDPE_PROJECT_SUITE = 'pgs_inv_GFL_inverter';

PGS_INV_GFL_IRIS_SDPE_PROJECT_VERSION = '1.1.0';

PGS_INV_GFL_IRIS_SDPE_PROJECT_UPDATED_AT = '2026-07-27';

%% Hardware macros
IRIS_F280039C_ID = 'iris_f280039c_node';

IRIS_F280039C_SCHEMA = 'iris_c2000_core_board';

IRIS_F280039C_NAME = 'IRIS F280039C Core Board';

% C2000 device name.
IRIS_F280039C_CHIP = 'TMS320F280039C';

% SysConfig source file used by this binding.
IRIS_F280039C_SYSCFG_FILE = 'ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg';

% SysConfig EPWM1 base macro.
IRIS_F280039C_EPWM1_BASE = 'IRIS_EPWM1_BASE';

% SysConfig EPWM2 base macro.
IRIS_F280039C_EPWM2_BASE = 'IRIS_EPWM2_BASE';

% SysConfig ADC channel 1 macro.
IRIS_F280039C_ADC_CH1 = 'ADC_CH1';

% SysConfig ADC channel 2 macro.
IRIS_F280039C_ADC_CH2 = 'ADC_CH2';

% SysConfig ADC channel 3 macro.
IRIS_F280039C_ADC_CH3 = 'ADC_CH3';

% SysConfig ADC channel 4 macro.
IRIS_F280039C_ADC_CH4 = 'ADC_CH4';

INN100E0016A_ID = 'inn100e0016a';

INN100E0016A_SCHEMA = 'power_switch';

INN100E0016A_NAME = 'INN100E0016A (identity requires BOM confirmation)';

% Power device part number.
INN100E0016A_PART_NUMBER = 'INN100E0016A';

% MOSFET, IGBT, GaN, SiC, etc.
INN100E0016A_DEVICE_TYPE = 'GaN FET';

% Drain-source or collector-emitter voltage rating.
INN100E0016A_VOLTAGE_RATING_V = 100.0;

% Current rating.
INN100E0016A_CURRENT_RATING_A = 0.0;

% On resistance.
INN100E0016A_RDSON_OHM = 0.016;

% Single switch, dual switch, half bridge power block, etc.
INN100E0016A_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
INN100E0016A_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
INN100E0016A_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
INN100E0016A_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
INN100E0016A_PACKAGE = 'unknown';

TMCS1133_B4A_ID = 'tmcs1133_b4a';

TMCS1133_B4A_SCHEMA = 'current_sensor';

TMCS1133_B4A_NAME = 'TMCS1133B4A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B4A_CHIP = 'TMCS1133B4A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B4A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B4A_RANGE_A = 15.5;

% Minimum output voltage.
TMCS1133_B4A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B4A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B4A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B4A_SENSITIVITY_MV_PER_A = 100.0;

% Typical small-signal bandwidth.
TMCS1133_B4A_BANDWIDTH_HZ = 1000000.0;

% Sensor internal series resistance.
TMCS1133_B4A_INTERNAL_RESISTANCE_OHM = 0.0007;

% Current sensor sensitivity converted to V/A.
TMCS1133_B4A_SENSITIVITY_V_PER_A = TMCS1133_B4A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B4A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B4A_BIAS_V / TMCS1133_B4A_SENSITIVITY_V_PER_A;

GMP_HELIOS_3PHGANINV_LV_ID = 'gmp_helios_3phganinv_lv';

GMP_HELIOS_3PHGANINV_LV_SCHEMA = 'inverter_3ph';

GMP_HELIOS_3PHGANINV_LV_NAME = 'GMP Helios 3PhGaNInv LV';

% Board name.
GMP_HELIOS_3PHGANINV_LV_BOARD_NAME = 'GMP Helios 3PhGaNInv LV';

% Gate driver or integrated driver.
GMP_HELIOS_3PHGANINV_LV_GATE_DRIVER = 'INS2001FQ';

% discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
GMP_HELIOS_3PHGANINV_LV_POWER_STAGE_KIND = 'discrete_gan';

% Minimum documented operating bus voltage; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_VBUS_MIN_V = 12.0;

% Maximum documented operating bus voltage; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_VBUS_MAX_V = 90.0;

% Board continuous RMS current; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_CURRENT_MAX_RMS_A = 25.0;

% Board peak current; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_CURRENT_MAX_PEAK_A = 35.0;

% PWM control inputs (3 or 6); zero means not verified.
GMP_HELIOS_3PHGANINV_LV_PWM_INPUT_COUNT = 6;

% One active-high, zero active-low.
GMP_HELIOS_3PHGANINV_LV_PWM_ACTIVE_LEVEL = 1;

% One only when PWM polarity was checked against a primary schematic or datasheet.
GMP_HELIOS_3PHGANINV_LV_PWM_POLARITY_VERIFIED = 0;

% Enable polarity; one active-high, zero active-low.
GMP_HELIOS_3PHGANINV_LV_ENABLE_ACTIVE_LEVEL = 1;

% Independently measurable motor phase-current channels.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_CHANNEL_COUNT = 3;

% SENSOR_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_SENSE_TYPE = 'SENSOR_TYPE_HALL';

% CS_TOPOLOGY_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_SENSE_TOPOLOGY = 'CS_TOPOLOGY_INLINE';

% Per-channel shunt resistance; zero for sensor IC or unknown.
GMP_HELIOS_3PHGANINV_LV_PH_SHUNT_RESISTANCE_OHM = 0.0;

% Current signal-chain gain; zero means configurable/unknown.
GMP_HELIOS_3PHGANINV_LV_PH_CSA_GAIN_V_V = 0.0;

% Zero-current ADC bias; zero may mean differential/unknown.
GMP_HELIOS_3PHGANINV_LV_PH_CSA_BIAS_V = 0.0;

% DC-link current measurement channels.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_CHANNEL_COUNT = 1;

% SENSOR_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_TYPE = 'SENSOR_TYPE_SHUNT';

% CS_TOPOLOGY_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_TOPOLOGY = 'CS_TOPOLOGY_DC_LINK';

% DC-link shunt resistance.
GMP_HELIOS_3PHGANINV_LV_DCBUS_SHUNT_RESISTANCE_OHM = 0.0003;

% Measured phase-voltage channels.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_CHANNEL_COUNT = 3;

% VS_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_TYPE = 'VS_TYPE_PHASE_GND';

% Phase-voltage divider or signal-chain gain; zero means unknown.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_GAIN = 0.0;

% Phase-voltage signal bias.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_BIAS_V = 0.0;

% DC-bus voltage channels.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_CHANNEL_COUNT = 1;

% VS_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_TYPE = 'VS_TYPE_PHASE_GND';

% DC-bus voltage divider or signal-chain gain; zero means unknown.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_GAIN = 0.0;

% DC-bus voltage signal bias.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_BIAS_V = 0.0;

% DC-link current sensitivity; one is the compatibility value when absent.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_GAIN = 1.0;

% DC-link current signal bias.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_BIAS_V = 0.0;

% Power-stage temperature channels.
GMP_HELIOS_3PHGANINV_LV_THERMAL_CHANNEL_COUNT = 0;

% verified, partial, schematic_required or template.
GMP_HELIOS_3PHGANINV_LV_VERIFICATION_STATUS = 'partial_bom_confirmation_required';

% Primary board manual, schematic or internal design reference.
GMP_HELIOS_3PHGANINV_LV_SOURCE_REFERENCE = 'Internal INN_LV3PHGAN schematic; legacy TMCS1133A4B text normalized to B4A electrical option';

% At least one phase-current channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_PHASE_CURRENT_SENSE = GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_CHANNEL_COUNT > 0;

% A DC-link current channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_DCBUS_CURRENT_SENSE = GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_CHANNEL_COUNT > 0;

% At least one phase-voltage channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_PHASE_VOLTAGE_SENSE = GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_CHANNEL_COUNT > 0;

% A DC-bus voltage channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_DCBUS_VOLTAGE_SENSE = GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_CHANNEL_COUNT > 0;

TLE4971A025_ID = 'tle4971a025';

TLE4971A025_SCHEMA = 'current_sensor';

TLE4971A025_NAME = 'TLE4971A025 Coreless Hall Current Sensor';

% Main sensing IC or technology name.
TLE4971A025_CHIP = 'TLE4971A025';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TLE4971A025_SENSOR_TYPE = 'Coreless Hall';

% Nominal measurable current range.
TLE4971A025_RANGE_A = 25.0;

% Minimum output voltage.
TLE4971A025_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TLE4971A025_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TLE4971A025_BIAS_V = 1.65;

% Current sensor sensitivity.
TLE4971A025_SENSITIVITY_MV_PER_A = 48.0;

% Typical small-signal bandwidth.
TLE4971A025_BANDWIDTH_HZ = 210000.0;

% Sensor internal series resistance.
TLE4971A025_INTERNAL_RESISTANCE_OHM = 0.0;

% Current sensor sensitivity converted to V/A.
TLE4971A025_SENSITIVITY_V_PER_A = TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TLE4971A025_MAX_CURRENT_FROM_BIAS_A = TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A;

HARMONIA_3PH_LC_FILTER_ID = 'gmp_harmonia_3ph_lc_filter';

HARMONIA_3PH_LC_FILTER_SCHEMA = 'Harmonia_3ph_LC_filter';

HARMONIA_3PH_LC_FILTER_NAME = 'GMP Harmonia 3-Phase LC Filter';

% Main filter inductance.
HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = 0.0015;

% Main filter capacitance.
HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = 0.000005;

% Board or module name.
HARMONIA_3PH_LC_FILTER_BOARD_NAME = 'Harmonia 3Ph LC Filter';

% Maximum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = 1000.0;

% Minimum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = 0.0;

% Maximum continuous RMS current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = 40.0;

% Maximum peak current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A * 1.41421356237;

% Recommended maximum PCB operating temperature.
HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = 85.0;

% Phase current sensor type enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = 2;

% Phase current sensing topology enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = 3;

% Phase voltage sensing type enum.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = 1;

% Phase current sensor bandwidth.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = TLE4971A025_BANDWIDTH_HZ;

% Total high-side voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = 3920000.0;

% Bottom voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = 560000.0;

% Isolation amplifier voltage gain.
HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = 0.4;

% Voltage sensing op-amp feedback resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = 1650.0;

% Voltage sensing op-amp input resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = 2000.0;

% ADC bias for phase voltage sensing.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = 1.65;

% Approximate phase voltage sense bandwidth.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = 100000.0;

% Phase voltage sensor model.
HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = ResDiv + AMC1350 + TLV9061;

% Calculated phase voltage sense gain.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = (HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM / (HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM + HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM)) * HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V * (HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM / HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);

% Phase current sensor model.
HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = Infineon TLE4971A025;

% Phase current sensor sensitivity.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = TLE4971A025_SENSITIVITY_MV_PER_A;

% Zero-current output bias.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = TLE4971A025_BIAS_V;

%% PWM
% IRIS Helios gate path uses the validated inverted PWM command polarity.
PWM_MODULATOR_USING_NEGATIVE_LOGIC = 1;

%% Commissioning
% Incremental control level; level 5 enables the cascaded grid-connected P/Q power loop and level 6 selects stand-alone line-voltage control. Level 6 is synchronized from simulation for incremental bench validation and is not hardware-validated.
% Options: (1), (2), (3), (4), (5), (6)
BUILD_LEVEL = 6;

%% Sampling
% Number of directly sampled phase currents.
% Options: (2), (3)
GFL_CURRENT_SAMPLE_PHASE_MODE = 3;

% Number of directly sampled phase voltages.
% Options: (2), (3)
GFL_VOLTAGE_SAMPLE_PHASE_MODE = 3;

%% PWM Hardware Binding
% Logical phase-U PWM resource; current SysConfig maps IRIS_EPWM1 to physical ePWM2 on GPIO2/GPIO3.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_U_BASE = 'IRIS_EPWM1_BASE';

% Logical phase-V PWM resource; current SysConfig maps IRIS_EPWM2 to physical ePWM1 on GPIO0/GPIO1.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_V_BASE = 'IRIS_EPWM2_BASE';

% Logical phase-W PWM resource; current SysConfig maps IRIS_EPWM3 to physical ePWM4 on GPIO22/GPIO7.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_W_BASE = 'IRIS_EPWM3_BASE';

% Helios gate-driver enable GPIO; current SysConfig maps IRIS_GPIO1 to GPIO58.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_ENABLE_PORT = 'IRIS_GPIO5';

% Helios gate-driver reset GPIO; current SysConfig maps IRIS_GPIO3 to GPIO40.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_RESET_PORT = 'IRIS_GPIO3';

%% Status GPIO Binding
% System status LED resource.
% Options: IRIS_LED1, IRIS_LED2
SYSTEM_LED = 'IRIS_LED1';

% Controller status LED resource.
% Options: IRIS_LED1, IRIS_LED2
CONTROLLER_LED = 'IRIS_LED2';

%% Output Voltage Sampling
% Phase-A output-voltage ADC result register base; keep paired with INV_UA.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UA_RESULT_BASE = 'ADC_CH1_RESULT_BASE';

% Phase-A output-voltage sample; current SysConfig binding is ADCA SOC0 / ADCIN6.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UA = 'ADC_CH1';

% Phase-B output-voltage ADC result register base; keep paired with INV_UB.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UB_RESULT_BASE = 'ADC_CH2_RESULT_BASE';

% Phase-B output-voltage sample; current SysConfig binding is ADCC SOC0 / ADCIN6.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UB = 'ADC_CH2';

% Phase-C output-voltage ADC result register base; keep paired with INV_UC.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UC_RESULT_BASE = 'ADC_CH3_RESULT_BASE';

% Phase-C output-voltage sample; current SysConfig binding is ADCB SOC0 / ADCIN3.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UC = 'ADC_CH3';

%% Output Current Sampling
% Phase-A output-current ADC result register base; keep paired with INV_IA.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IA_RESULT_BASE = 'ADC_CH4_RESULT_BASE';

% Phase-A output-current sample; current SysConfig binding is ADCC SOC1 / ADCIN9.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IA = 'ADC_CH4';

% Phase-B output-current ADC result register base; keep paired with INV_IB.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IB_RESULT_BASE = 'ADC_CH5_RESULT_BASE';

% Phase-B output-current sample; current SysConfig binding is ADCA SOC1 / ADCIN3.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IB = 'ADC_CH5';

% Phase-C output-current ADC result register base; keep paired with INV_IC.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IC_RESULT_BASE = 'ADC_CH6_RESULT_BASE';

% Phase-C output-current sample; current SysConfig binding is ADCC SOC2 / ADCIN4.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IC = 'ADC_CH6';

%% Bridge Voltage Sampling
% Phase-U bridge-voltage ADC result register base; keep paired with INV_UU.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UU_RESULT_BASE = 'ADC_CH9_RESULT_BASE';

% Phase-U bridge-voltage sample; current SysConfig binding is ADCA SOC2 / ADCIN12.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UU = 'ADC_CH9';

% Phase-V bridge-voltage ADC result register base; keep paired with INV_UV.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UV_RESULT_BASE = 'ADC_CH10_RESULT_BASE';

% Phase-V bridge-voltage sample; current SysConfig binding is ADCC SOC3 / ADCIN1.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UV = 'ADC_CH10';

% Phase-W bridge-voltage ADC result register base; keep paired with INV_UW.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_UW_RESULT_BASE = 'ADC_CH11_RESULT_BASE';

% Phase-W bridge-voltage sample; current SysConfig binding is ADCB SOC3 / ADCIN11.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_UW = 'ADC_CH11';

%% Bridge Current Sampling
% Phase-U bridge-current ADC result register base; currently aliases output-current channel INV_IA.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IU_RESULT_BASE = 'ADC_CH4_RESULT_BASE';

% Phase-U bridge-current sample; currently aliases output-current channel INV_IA.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IU = 'ADC_CH4';

% Phase-V bridge-current ADC result register base; currently aliases output-current channel INV_IB.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IV_RESULT_BASE = 'ADC_CH5_RESULT_BASE';

% Phase-V bridge-current sample; currently aliases output-current channel INV_IB.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IV = 'ADC_CH5';

% Phase-W bridge-current ADC result register base; currently aliases output-current channel INV_IC.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IW_RESULT_BASE = 'ADC_CH6_RESULT_BASE';

% Phase-W bridge-current sample; currently aliases output-current channel INV_IC.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IW = 'ADC_CH6';

%% DC Bus Sampling
% DC-bus voltage ADC result register base; keep paired with INV_VBUS.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_VBUS_RESULT_BASE = 'ADC_CH7_RESULT_BASE';

% DC-bus voltage sample; current SysConfig binding is ADCB SOC1 / ADCIN10.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_VBUS = 'ADC_CH7';

% DC-bus current ADC result register base; keep paired with INV_IBUS.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IBUS_RESULT_BASE = 'ADC_CH8_RESULT_BASE';

% DC-bus current sample; current SysConfig binding is ADCB SOC2 / ADCIN12.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IBUS = 'ADC_CH8';

%% Requirement bindings
% Current-loop and PWM update frequency in hertz.
CONTROLLER_FREQUENCY = 20e3;

% IRIS ePWM compare range at 20 kHz.
CTRL_PWM_CMP_MAX = 3000 - 1;

% IRIS ePWM dead-band count.
CTRL_PWM_DEADBAND_CMP = 50;

% F280039C system clock in hertz.
CTRL_SYS_FREQUENCY = 120e6;

% C2000 millisecond tick divider.
DSP_C2000_DSP_TIME_DIV = CTRL_SYS_FREQUENCY / 1000 / CTRL_PWM_CMP_MAX / 2;

% ADC reference voltage synchronized with the SysConfig external 2.5-V reference selection.
CTRL_ADC_VOLTAGE_REF = 3.3;

% DC-bus per-unit voltage base.
CTRL_DCBUS_VOLTAGE = 60.0;

% SVPWM phase-voltage base.
CTRL_VOLTAGE_BASE = CTRL_DCBUS_VOLTAGE / 1.73205081;

% Phase-current per-unit base in amperes.
CTRL_CURRENT_BASE = 10.0;

% Grid-filter inductance from the selected Harmonia entity.
GFL_GRID_FILTER_INDUCTANCE_H = HARMONIA_3PH_LC_FILTER_INDUCTANCE_H;

% Grid-filter capacitance from the selected Harmonia entity.
GFL_GRID_FILTER_CAPACITANCE_F = HARMONIA_3PH_LC_FILTER_CAPACITANCE_F;

% DC-link voltage sensing gain.
CTRL_DC_VOLTAGE_SENSITIVITY = 0.02738589;

% DC-link voltage sensing bias.
CTRL_DC_VOLTAGE_BIAS = 0.0;

% Grid-voltage sensing gain.
CTRL_GRID_VOLTAGE_SENSITIVITY = 0.00139154;

% Grid-voltage sensing bias.
CTRL_GRID_VOLTAGE_BIAS = 1.65;

% Helios phase-voltage sensing gain.
CTRL_INVERTER_VOLTAGE_SENSITIVITY = 0.02738589;

% Helios phase-voltage sensing bias.
CTRL_INVERTER_VOLTAGE_BIAS = 0.0;

% DC-link current sensitivity in volts per ampere.
CTRL_DC_CURRENT_SENSITIVITY = 0.15;

% DC-link current zero bias.
CTRL_DC_CURRENT_BIAS = 1.65;

% Grid-current sensitivity in volts per ampere.
CTRL_GRID_CURRENT_SENSITIVITY = 0.15;

% Grid-current zero bias.
CTRL_GRID_CURRENT_BIAS = HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V;

% Validated Helios phase-current sensitivity in volts per ampere.
CTRL_INVERTER_CURRENT_SENSITIVITY = 0.05;

% Helios phase-current zero bias.
CTRL_INVERTER_CURRENT_BIAS = 1.65;

% Startup delay in milliseconds.
CTRL_STARTUP_DELAY = 100;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
