%% SDPE MATLAB initialization script
% Project: PGS GFL Inverter Simulation
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Host simulation timing and sensing settings for the common GFL controller.

%% Project metadata
PGS_INV_GFL_SIM_SDPE_PROJECT_ID = 'pgs_inv_gfl_simulate';

PGS_INV_GFL_SIM_SDPE_PROJECT_SUITE = 'pgs_inv_GFL_inverter';

PGS_INV_GFL_SIM_SDPE_PROJECT_VERSION = '1.0.0';

PGS_INV_GFL_SIM_SDPE_PROJECT_UPDATED_AT = '2026-07-21';

%% Hardware macros
INN100E0016A_ID = 'inn100e0016a';

INN100E0016A_SCHEMA = 'power_switch';

INN100E0016A_NAME = 'INN100E0016A (identity requires BOM confirmation)';

% Power device part number.
INN100E0016A_PART_NUMBER = 'INN100E0016A';

% MOSFET, IGBT, GaN, SiC, etc.
INN100E0016A_DEVICE_TYPE = 'GaN FET';

% Drain-source or collector-emitter voltage rating.
INN100E0016A_VOLTAGE_RATING_V = 100.0;

% Current rating.
INN100E0016A_CURRENT_RATING_A = 0.0;

% On resistance.
INN100E0016A_RDSON_OHM = 0.016;

% Single switch, dual switch, half bridge power block, etc.
INN100E0016A_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
INN100E0016A_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
INN100E0016A_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
INN100E0016A_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
INN100E0016A_PACKAGE = 'unknown';

TMCS1133_B4A_ID = 'tmcs1133_b4a';

TMCS1133_B4A_SCHEMA = 'current_sensor';

TMCS1133_B4A_NAME = 'TMCS1133B4A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B4A_CHIP = 'TMCS1133B4A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B4A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B4A_RANGE_A = 15.5;

% Minimum output voltage.
TMCS1133_B4A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B4A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B4A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B4A_SENSITIVITY_MV_PER_A = 100.0;

% Typical small-signal bandwidth.
TMCS1133_B4A_BANDWIDTH_HZ = 1000000.0;

% Sensor internal series resistance.
TMCS1133_B4A_INTERNAL_RESISTANCE_OHM = 0.0007;

% Current sensor sensitivity converted to V/A.
TMCS1133_B4A_SENSITIVITY_V_PER_A = TMCS1133_B4A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B4A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B4A_BIAS_V / TMCS1133_B4A_SENSITIVITY_V_PER_A;

GMP_HELIOS_3PHGANINV_LV_ID = 'gmp_helios_3phganinv_lv';

GMP_HELIOS_3PHGANINV_LV_SCHEMA = 'inverter_3ph';

GMP_HELIOS_3PHGANINV_LV_NAME = 'GMP Helios 3PhGaNInv LV';

% Board name.
GMP_HELIOS_3PHGANINV_LV_BOARD_NAME = 'GMP Helios 3PhGaNInv LV';

% Gate driver or integrated driver.
GMP_HELIOS_3PHGANINV_LV_GATE_DRIVER = 'INS2001FQ';

% discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
GMP_HELIOS_3PHGANINV_LV_POWER_STAGE_KIND = 'discrete_gan';

% Minimum documented operating bus voltage; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_VBUS_MIN_V = 12.0;

% Maximum documented operating bus voltage; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_VBUS_MAX_V = 90.0;

% Board continuous RMS current; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_CURRENT_MAX_RMS_A = 25.0;

% Board peak current; zero means unspecified.
GMP_HELIOS_3PHGANINV_LV_CURRENT_MAX_PEAK_A = 35.0;

% PWM control inputs (3 or 6); zero means not verified.
GMP_HELIOS_3PHGANINV_LV_PWM_INPUT_COUNT = 6;

% One active-high, zero active-low.
GMP_HELIOS_3PHGANINV_LV_PWM_ACTIVE_LEVEL = 1;

% One only when PWM polarity was checked against a primary schematic or datasheet.
GMP_HELIOS_3PHGANINV_LV_PWM_POLARITY_VERIFIED = 0;

% Enable polarity; one active-high, zero active-low.
GMP_HELIOS_3PHGANINV_LV_ENABLE_ACTIVE_LEVEL = 1;

% Independently measurable motor phase-current channels.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_CHANNEL_COUNT = 3;

% SENSOR_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_SENSE_TYPE = 'SENSOR_TYPE_HALL';

% CS_TOPOLOGY_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_SENSE_TOPOLOGY = 'CS_TOPOLOGY_INLINE';

% Per-channel shunt resistance; zero for sensor IC or unknown.
GMP_HELIOS_3PHGANINV_LV_PH_SHUNT_RESISTANCE_OHM = 0.0;

% Current signal-chain gain; zero means configurable/unknown.
GMP_HELIOS_3PHGANINV_LV_PH_CSA_GAIN_V_V = 0.0;

% Zero-current ADC bias; zero may mean differential/unknown.
GMP_HELIOS_3PHGANINV_LV_PH_CSA_BIAS_V = 0.0;

% DC-link current measurement channels.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_CHANNEL_COUNT = 1;

% SENSOR_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_TYPE = 'SENSOR_TYPE_SHUNT';

% CS_TOPOLOGY_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_TOPOLOGY = 'CS_TOPOLOGY_DC_LINK';

% DC-link shunt resistance.
GMP_HELIOS_3PHGANINV_LV_DCBUS_SHUNT_RESISTANCE_OHM = 0.0003;

% Measured phase-voltage channels.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_CHANNEL_COUNT = 3;

% VS_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_TYPE = 'VS_TYPE_PHASE_GND';

% Phase-voltage divider or signal-chain gain; zero means unknown.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_GAIN = 0.0;

% Phase-voltage signal bias.
GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_SENSE_BIAS_V = 0.0;

% DC-bus voltage channels.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_CHANNEL_COUNT = 1;

% VS_TYPE_* constant.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_TYPE = 'VS_TYPE_PHASE_GND';

% DC-bus voltage divider or signal-chain gain; zero means unknown.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_GAIN = 0.0;

% DC-bus voltage signal bias.
GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_SENSE_BIAS_V = 0.0;

% DC-link current sensitivity; one is the compatibility value when absent.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_GAIN = 1.0;

% DC-link current signal bias.
GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_SENSE_BIAS_V = 0.0;

% Power-stage temperature channels.
GMP_HELIOS_3PHGANINV_LV_THERMAL_CHANNEL_COUNT = 0;

% verified, partial, schematic_required or template.
GMP_HELIOS_3PHGANINV_LV_VERIFICATION_STATUS = 'partial_bom_confirmation_required';

% Primary board manual, schematic or internal design reference.
GMP_HELIOS_3PHGANINV_LV_SOURCE_REFERENCE = 'Internal INN_LV3PHGAN schematic; legacy TMCS1133A4B text normalized to B4A electrical option';

% At least one phase-current channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_PHASE_CURRENT_SENSE = GMP_HELIOS_3PHGANINV_LV_PH_CURRENT_CHANNEL_COUNT > 0;

% A DC-link current channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_DCBUS_CURRENT_SENSE = GMP_HELIOS_3PHGANINV_LV_DCBUS_CURRENT_CHANNEL_COUNT > 0;

% At least one phase-voltage channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_PHASE_VOLTAGE_SENSE = GMP_HELIOS_3PHGANINV_LV_PH_VOLTAGE_CHANNEL_COUNT > 0;

% A DC-bus voltage channel is present.
GMP_HELIOS_3PHGANINV_LV_HAS_DCBUS_VOLTAGE_SENSE = GMP_HELIOS_3PHGANINV_LV_DCBUS_VOLTAGE_CHANNEL_COUNT > 0;

TLE4971A025_ID = 'tle4971a025';

TLE4971A025_SCHEMA = 'current_sensor';

TLE4971A025_NAME = 'TLE4971A025 Coreless Hall Current Sensor';

% Main sensing IC or technology name.
TLE4971A025_CHIP = 'TLE4971A025';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TLE4971A025_SENSOR_TYPE = 'Coreless Hall';

% Nominal measurable current range.
TLE4971A025_RANGE_A = 25.0;

% Minimum output voltage.
TLE4971A025_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TLE4971A025_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TLE4971A025_BIAS_V = 1.65;

% Current sensor sensitivity.
TLE4971A025_SENSITIVITY_MV_PER_A = 48.0;

% Typical small-signal bandwidth.
TLE4971A025_BANDWIDTH_HZ = 210000.0;

% Sensor internal series resistance.
TLE4971A025_INTERNAL_RESISTANCE_OHM = 0.0;

% Current sensor sensitivity converted to V/A.
TLE4971A025_SENSITIVITY_V_PER_A = TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TLE4971A025_MAX_CURRENT_FROM_BIAS_A = TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A;

HARMONIA_3PH_LC_FILTER_ID = 'gmp_harmonia_3ph_lc_filter';

HARMONIA_3PH_LC_FILTER_SCHEMA = 'Harmonia_3ph_LC_filter';

HARMONIA_3PH_LC_FILTER_NAME = 'GMP Harmonia 3-Phase LC Filter';

% Main filter inductance.
HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = 0.0015;

% Main filter capacitance.
HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = 0.000005;

% Board or module name.
HARMONIA_3PH_LC_FILTER_BOARD_NAME = 'Harmonia 3Ph LC Filter';

% Maximum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = 1000.0;

% Minimum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = 0.0;

% Maximum continuous RMS current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = 40.0;

% Maximum peak current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A * 1.41421356237;

% Recommended maximum PCB operating temperature.
HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = 85.0;

% Phase current sensor type enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = 2;

% Phase current sensing topology enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = 3;

% Phase voltage sensing type enum.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = 1;

% Phase current sensor bandwidth.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = TLE4971A025_BANDWIDTH_HZ;

% Total high-side voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = 3920000.0;

% Bottom voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = 560000.0;

% Isolation amplifier voltage gain.
HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = 0.4;

% Voltage sensing op-amp feedback resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = 1650.0;

% Voltage sensing op-amp input resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = 2000.0;

% ADC bias for phase voltage sensing.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = 1.65;

% Approximate phase voltage sense bandwidth.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = 100000.0;

% Phase voltage sensor model.
HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = ResDiv + AMC1350 + TLV9061;

% Calculated phase voltage sense gain.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = (HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM / (HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM + HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM)) * HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V * (HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM / HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);

% Phase current sensor model.
HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = Infineon TLE4971A025;

% Phase current sensor sensitivity.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = TLE4971A025_SENSITIVITY_MV_PER_A;

% Zero-current output bias.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = TLE4971A025_BIAS_V;

%% Commissioning
% Incremental control level; level 5 enables the cascaded P/Q power loop.
% Options: (1), (2), (3), (4), (5)
BUILD_LEVEL = 5;

%% Sampling
% Number of directly sampled phase currents.
% Options: (2), (3)
GFL_CURRENT_SAMPLE_PHASE_MODE = 3;

% Simulation supplies two independent phase-voltage samples.
% Options: (2), (3)
GFL_VOLTAGE_SAMPLE_PHASE_MODE = 2;

%% Requirement bindings
% Simulation control step frequency.
CONTROLLER_FREQUENCY = 20e3;

% Virtual PWM compare range.
CTRL_PWM_CMP_MAX = 3000;

% Virtual PWM dead-band count.
CTRL_PWM_DEADBAND_CMP = 50;

% Virtual ADC reference.
CTRL_ADC_VOLTAGE_REF = 3.3;

% DC-bus voltage base.
CTRL_DCBUS_VOLTAGE = 55.0;

% SVPWM phase-voltage base.
CTRL_VOLTAGE_BASE = CTRL_DCBUS_VOLTAGE / 1.73205081;

% Phase-current base.
CTRL_CURRENT_BASE = 10.0;

% Harmonia inductance.
GFL_GRID_FILTER_INDUCTANCE_H = HARMONIA_3PH_LC_FILTER_INDUCTANCE_H;

% Harmonia capacitance.
GFL_GRID_FILTER_CAPACITANCE_F = HARMONIA_3PH_LC_FILTER_CAPACITANCE_F;

% DC voltage gain.
CTRL_DC_VOLTAGE_SENSITIVITY = 0.02738589;

% DC voltage bias.
CTRL_DC_VOLTAGE_BIAS = 0.0;

% Grid-voltage gain.
CTRL_GRID_VOLTAGE_SENSITIVITY = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN;

% Grid-voltage bias.
CTRL_GRID_VOLTAGE_BIAS = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V;

% Converter voltage gain.
CTRL_INVERTER_VOLTAGE_SENSITIVITY = 0.02738589;

% Converter voltage bias.
CTRL_INVERTER_VOLTAGE_BIAS = 0.0;

% DC current sensitivity.
CTRL_DC_CURRENT_SENSITIVITY = 0.02475;

% DC current bias.
CTRL_DC_CURRENT_BIAS = 1.65;

% Grid-current sensitivity.
CTRL_GRID_CURRENT_SENSITIVITY = HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A * 0.001;

% Grid-current bias.
CTRL_GRID_CURRENT_BIAS = HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V;

% Converter current sensitivity.
CTRL_INVERTER_CURRENT_SENSITIVITY = 0.05;

% Converter current bias.
CTRL_INVERTER_CURRENT_BIAS = 1.65;

% Startup delay in milliseconds.
CTRL_STARTUP_DELAY = 50;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
